/**
 * Report generator — produces pi-review-report.md
 */
import type { GateState, Finding } from "./state";
import {
  LAYER_LABELS,
  LAYER_ICONS,
  SEVERITY_ICONS,
  SEVERITY_LABELS,
} from "./settings";
import * as fs from "node:fs";

export async function generateReport(gate: GateState): Promise<void> {
  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────────────
  lines.push("# 🔒 Pre-Push Gate Report");
  lines.push("");
  lines.push("| Field | Value |");
  lines.push("|-------|-------|");
  lines.push(
    `| **Date** | ${new Date(gate.startedAt).toISOString().replace("T", " ").slice(0, 19)} UTC |`
  );
  lines.push(`| **Base** | \`${gate.config.baseBranch}\` |`);

  if (gate.finishedAt) {
    const duration = ((gate.finishedAt - gate.startedAt) / 1000).toFixed(1);
    lines.push(`| **Duration** | ${duration}s |`);
  }

  const verdictIcon =
    gate.verdict === "pass" ? "✅ PASSED" : "⛔ BLOCKED";
  lines.push(`| **Verdict** | ${verdictIcon} |`);
  lines.push("");

  // ── Layer Summary ───────────────────────────────────────────────
  lines.push("---");
  lines.push("");
  lines.push("## 📊 Layer Summary");
  lines.push("");

  if (gate.layers.length === 0) {
    lines.push("*No layers executed*");
  } else {
    for (const layer of gate.layers) {
      const icon = LAYER_ICONS[layer.layer] ?? "•";
      const label = LAYER_LABELS[layer.layer] ?? layer.layer;
      const status = layer.passed ? "✅" : "❌";
      const iterInfo =
        layer.iterations !== undefined
          ? ` (${layer.iterations} iterations)`
          : "";
      const modelInfo = layer.model ? ` · model: \`${layer.model}\`` : "";

      lines.push(
        `### ${icon} ${label} ${status}${iterInfo}${modelInfo}`
      );
      lines.push(`> ${layer.summary}`);
      lines.push("");

      if (layer.findings.length > 0) {
        lines.push("| # | Severity | File | Finding |");
        lines.push("|---|----------|------|---------|");
        layer.findings.forEach((f, i) => {
          const sevIcon = SEVERITY_ICONS[f.severity] ?? "•";
          const location = f.file
            ? `\`${f.file}${f.line ? `:${f.line}` : ""}\``
            : "—";
          const resolved = f.resolved ? " ~~" : "";
          lines.push(
            `| ${i + 1} | ${sevIcon} ${f.severity} | ${location} |${resolved} ${f.message} |`
          );
          if (f.suggestion) {
            lines.push(`| | | | → *${f.suggestion}* |`);
          }
        });
        lines.push("");
      }
    }
  }

  // ── All Findings ────────────────────────────────────────────────
  const allFindings = gate.layers.flatMap((l) => l.findings);
  const unresolved = allFindings.filter((f) => !f.resolved);
  const critical = unresolved.filter((f) => f.severity === "critical");
  const warns = unresolved.filter((f) => f.severity === "warn");
  const infos = unresolved.filter((f) => f.severity === "info");

  if (unresolved.length > 0) {
    lines.push("---");
    lines.push("");
    lines.push("## 🔍 Unresolved Findings");
    lines.push("");
    lines.push(
      `| Severity | Count | Action |`
    );
    lines.push(`|----------|-------|--------|`);
    lines.push(`| 🔴 Critical (P0) | ${critical.length} | **BLOCK push** |`);
    lines.push(`| ⚠️ Warn (P1) | ${warns.length} | Required review |`);
    lines.push(`| ℹ️ Info (P2) | ${infos.length} | Non-blocking |`);
    lines.push("");

    function printFindings(title: string, findings: Finding[]) {
      if (findings.length === 0) return;
      lines.push(`### ${title}`);
      lines.push("");
      for (const f of findings) {
        const icon = SEVERITY_ICONS[f.severity];
        lines.push(`#### ${icon} ${f.id}: ${f.message}`);
        if (f.file) {
          lines.push(`- **Location:** \`${f.file}${f.line ? `:${f.line}` : ""}\``);
        }
        if (f.suggestion) {
          lines.push(`- **Suggestion:** ${f.suggestion}`);
        }
        lines.push("");
      }
    }

    printFindings("🔴 Critical (P0) — Blocking", critical);
    printFindings("⚠️ Warnings (P1)", warns);
    printFindings("ℹ️ Info (P2)", infos);
  }

  // ── Actions ─────────────────────────────────────────────────────
  lines.push("---");
  lines.push("");
  lines.push("## 🎯 Actions");
  lines.push("");

  if (gate.verdict === "pass") {
    lines.push("- ✅ All gates passed — safe to push");
    lines.push("- Run `git push` to deploy");
    if (gate.config.autoPushOnPass) {
      lines.push("- ⚡ Auto-push was triggered automatically");
    }
  } else {
    lines.push("- ⛔ Gate blocked — fix issues below before pushing");
    lines.push("- After fixes, run `/gate` again to re-validate");
    lines.push("- To bypass: `git push --no-verify`");
  }

  lines.push("");
  lines.push(
    `*Report generated by pi-sentinel v1.0.0 at ${new Date().toISOString()}*`
  );

  // Write
  const reportPath = gate.reportPath;
  fs.writeFileSync(reportPath, lines.join("\n"), "utf-8");
}


/**
 * Escape pipe characters for markdown table cells
 */
function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\n/g, " ");
}